### PR TITLE
fix(language-core): transform slot parameter list into equivalent binding pattern

### LINKED ISSUE #5243: emitting declarations for a single file adds global declarations which have ts errors
### Vue - Official extension or vue-tsc version

2.2.8

### VSCode version

1.97.2

### Vue version

3.5.13

### TypeScript version

5.7.3

### System Info

```shell
System:
    OS: macOS 15.3.1
    CPU: (10) arm64 Apple M2 Pro
    Memory: 107.77 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 23.7.0 - ~/.local/state/fnm_multishells/42863_1740988676037/bin/node
    Yarn: 1.22.22 - ~/.local/state/fnm_multishells/42863_1740988676037/bin/yarn
    npm: 10.9.2 - ~/.local/state/fnm_multishells/42863_1740988676037/bin/npm
    pnpm: 9.15.4 - ~/.local/state/fnm_multishells/42863_1740988676037/bin/pnpm
    bun: 1.2.0 - /opt/homebrew/bin/bun
  Browsers:
    Safari: 18.3
```

### package.json dependencies

```json
{
  "private": true,
  "type": "module",
  "scripts": {
    "check": "rimraf dist && vue-tsc --declaration --emitDeclarationOnly src/App.vue --outFile dist/App.vue.d.ts"
  },
  "dependencies": {
    "vue": "^3.5.13"
  },
  "devDependencies": {
    "@tsconfig/node22": "^22.0.0",
    "@types/node": "^22.13.4",
    "@vitejs/plugin-vue": "^5.2.1",
    "@vue/tsconfig": "^0.7.0",
    "npm-run-all2": "^7.0.2",
    "rimraf": "^6.0.1",
    "typescript": "~5.7.3",
    "vite": "^6.1.0",
    "vite-plugin-vue-devtools": "^7.7.2",
    "vue-tsc": "^2.2.8"
  }
}
```

### Steps to reproduce

1. clone https://github.com/brc-dd/vue-tsc-ts-ignore-strip
2. run `pnpm i; pnpm check`
3. open `dist/App.vue.d.ts` to see errors

### What is expected?

The source has `// @ts-ignore` in these parts:

https://github.com/vuejs/language-tools/blob/9b6911a95f13905f5f41a78cbb369bb8f1e65dde/packages/language-core/lib/codegen/globalTypes.ts#L138-L141

These should be present in the output dist too. Or better fix those types if possible 👀 Or maybe not emit global types like when whole project is compiled.

### What is actually happening?

Those comments are getting stripped somewhere.

### Link to minimal reproduction

https://github.com/brc-dd/vue-tsc-ts-ignore-strip

### Any additional comments?

x-ref: https://github.com/vuejs/language-tools/issues/5232#issuecomment-2693267603

### PR DESCRIPTION
**Pull request by KazariEX**
fix #5243

### CODE REVIEW

**Comment by KazariEX** [comment]
@brc-dd Can this solve your problem?

File: packages/language-core/lib/codegen/globalTypes.ts [hunk 1]
```diff
@@ -135,10 +135,7 @@ export function generateGlobalTypes({
 		key: keyof T,
 		index: number,
 	][];
-	// @ts-ignore
-	function __VLS_getSlotParams<T>(slot: T): Parameters<__VLS_PickNotAny<NonNullable<T>, (...args: any[]) => any>>;
-	// @ts-ignore
-	function __VLS_getSlotParam<T>(slot: T): Parameters<__VLS_PickNotAny<NonNullable<T>, (...args: any[]) => any>>[0];
+	function __VLS_getSlotParameters<S, D extends S = S>(slot: S, decl?: D): Parameters<__VLS_PickNotAny<NonNullable<D>, (...args: any) => any>>;
```
Comment (brc-dd) [inline packages/language-core/lib/codegen/globalTypes.ts:138]: this still seems to be showing:

```
Type '__VLS_PickNotAny<NonNullable<D>, (...args: any) => any>' does not satisfy the constraint '(...args: any) => any'.
  Type 'NonNullable<D> | ((...args: any) => any)' is not assignable to type '(...args: any) => any'.
    Type 'NonNullable<D>' is not assignable to type '(...args: any) => any'.
      Type '{}' provides no match for the signature '(...args: any): any'.ts(2344)
```
