### PR TITLE
fix: avoid losing generic types

### LINKED ISSUE #3561: Generic SFC broken from 1.8.10, 1.8.11
I had a generic component that was working, but it isn't resolving correctly in version 1.8.10 and 1.8.11, but if I downgrade to 1.8.8, it works fine.

In this example in index.js, `item` is just resolving to `unknown`, which results in a lot of errors.

### index.vue
```JS
<CarouselSelect
  v-slot="{ item }"
  v-model="componentState.selected"
  :items="componentState.items"
  :get-key="(item) => item.id"
  class="mb-3"
>
  {{item.title}}
</CarouselSelect>
```

### CarouselSelect.vue
```JS
<script setup lang="ts" generic="T, TValue extends undefined|string|number|symbol">
const $props = defineProps<{
  items: Array<T>,
  modelValue: TValue,
  getKey: (item: T) => TValue,
}>();

defineSlots<{
  default: { item: T },
}>();
//...
</script>
```

### PR DESCRIPTION
**Pull request by so1ve**
close #3561

My implementation is terribly ugly so I need more time to refactor it.

### CODE REVIEW

File: packages/vue-language-core/src/utils/globalTypes.ts [hunk 1]
```diff
@@ -118,6 +118,8 @@ declare function __VLS_componentProps<T, K>(comp: T, fnReturn: K):
 	__VLS_PickNotAny<K, {}> extends { __ctx: { props: infer P } } ? NonNullable<P>
 	: T extends (props: infer P, ...args: any) => any ? NonNullable<P> :
 	{};
+
+declare function __VLS_cast<T>(x: T): T;
```
Comment (rchl) [inline packages/vue-language-core/src/utils/globalTypes.ts:124]: Does that really work? I would imagine that it would cause a type error when passed x doesn't match T. To cast it would need to take unknown argument or something

Comment (so1ve) [reply packages/vue-language-core/src/utils/globalTypes.ts:124]: @rchl Ahhhh this is not `casting` some type to another type. This function is created to make the error more reasonable:

https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXzCgGcMAeAFQD4AKDALnnIEoHyBuAKA7DxKRxzwAvPADe8KAwCM8AL4SiYiQxIwsqAOZz4Aeh2MAFlkVEDOAO6KMBhCBgwcMeDkTwMATwAOCHqgBudkS4qNy8GPAARrDCBMRk4pLwqupasjQJ0nJMuvrkRiZmlm428HYOTi5uXggAtsY1UBhgBhxAA
