### PR TITLE
fix: properly get components

### LINKED ISSUE #1886: A local component cannot override a global component
_Initial issue: nuxt/framework#7401_

It seems like Volar can't correctly find a type of Functional Component when it is used inside the template.

image

**Environment:**
VSCode + Volar + TakeOver mode 4.8.2

### PR DESCRIPTION
**Pull request by so1ve**
close #1886

### CODE REVIEW

File: packages/vue-test-workspace/vue-tsc/non-strict-template/#2157/main.vue [hunk 1]
```diff
@@ -0,0 +1,11 @@
+<script setup lang="ts">
+declare module 'vue' {
+  export interface GlobalComponents {
+    Transition: typeof import('vue')['Transition'];
+  }
+};
```
Comment (rchl) [inline packages/vue-test-workspace/vue-tsc/non-strict-template/#2157/main.vue:6]: Even though it's within a specific file, it will affect all tests, I believe.
If so then maybe use some more unique name so that there is no chance of affecting other tests with that?

**Comment by so1ve** [comment]
Just updated
