### PR TITLE
fix(language-core): ignore frontmatter block in markdown files

### LINKED ISSUE #5359: Ignore frontmatter in markdown files
### Vue - Official extension or vue-tsc version

3.0.0-alpha.7

### VSCode version

1.100.0

### Vue version

3.5.13

### TypeScript version

5.8.3

### System Info

```shell
System:
    OS: macOS 15.4.1
    CPU: (10) arm64 Apple M2 Pro
    Memory: 557.42 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 24.0.0 - ~/.local/state/fnm_multishells/70571_1746938934494/bin/node
    npm: 11.3.0 - ~/.local/state/fnm_multishells/70571_1746938934494/bin/npm
    pnpm: 10.10.0 - ~/.local/state/fnm_multishells/70571_1746938934494/bin/pnpm
    bun: 1.2.10 - /opt/homebrew/bin/bun
  Browsers:
    Safari: 18.4
    Safari Technology Preview: 18.4
```

### package.json dependencies

```json
{
  "devDependencies": {
    "vue-tsc": "next",
    "vue": "^3.5.13",
    "typescript": "^5.8.3"
  }
}
```

### Steps to reproduce

```md
---
outline: [2, 3]
---

# <p>[link](/#)</p>

lorem
```

Currently it shows:

Image

\
But if the frontmatter is changed to something like:

```md
---
outline: 3
---
```

then it works fine:

Image

### What is expected?

No error in the first case too.

### What is actually happening?

Unexpected error in first case. I think frontmatter should just be ignored if present? Maybe some regex like `/^---[\s\S]*?\n---(?:\r?\n|$)/` here:

https://github.com/vuejs/language-tools/blob/3b82afe0c816e87d29eb267b4b5e3c15593a21c4/packages/language-core/lib/plugins/file-md.ts#L38-L48

### Link to minimal reproduction

https://github.com/brc-dd/volar-frontmatter-bug

### Any additional comments?

from vue discord - https://discord.com/channels/325477692906536972/790509637598314527/1370932083060641877

### PR DESCRIPTION
**Pull request by brc-dd**
closes #5359

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -14,3 +14,5 @@ packages/*/*.map
 packages/*/lib/**/*.d.ts
 packages/*/lib/**/*.js
 packages/*/lib/**/*.map
+
+.DS_Store
```
Comment (KazariEX) [inline .gitignore:18]: https://github.com/vuejs/language-tools/pull/4722#issuecomment-2322813521

File: packages/language-core/lib/plugins/file-md.ts [hunk 2]
```diff
@@ -13,6 +13,7 @@ const sfcBlockReg = /\<(script|style)\b[\s\S]*?\>([\s\S]*?)\<\/\1\>/g;
 const angleBracketReg = /\<\S*\:\S*\>/g;
 const linkReg = /\[[\s\S]*?\]\([\s\S]*?\)/g;
 const codeSnippetImportReg = /^\s*<<<\s*.+/gm;
+const frontmatterReg = /^---[\s\S]*?\n---(?:\r?\n|$)/;
```
Comment (KazariEX) [inline packages/language-core/lib/plugins/file-md.ts:16]: Let's move it to the top to match the natural order of the syntax.

**Review by KazariEX — APPROVED** [review]
